using Newtonsoft.Json.Linq;
using System.Threading.Tasks;
using UnityEngine;

namespace com.csutil.ui.mtvmtv {

    /// <summary> A generic presenter that can be used with a view that was generated by a
    /// Json schema (see JsonSchemaToView) and can load a model instance via 
    /// presenter.LoadViaJsonIntoView(..) </summary>
    public class JObjectPresenter : Presenter<JObject> {

        public GameObject targetView { get; set; }
        public JsonSchemaToView vmtv;

        public JObjectPresenter(JsonSchemaToView vmtv) { this.vmtv = vmtv; }

        public async Task OnLoad(JObject root) { await targetView.LinkToJsonModel(root, vmtv); }

    }

}