//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuntimeNetCore {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuntimeNetCore.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} copying file &apos;{1}&apos; to &apos;{2}&apos;: {3}.
        /// </summary>
        public static string ErrorCopyingFile {
            get {
                return ResourceManager.GetString("ErrorCopyingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} creating directory &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorCreatingDirectory {
            get {
                return ResourceManager.GetString("ErrorCreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} creating file handle for file path &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorCreatingFileHandle {
            get {
                return ResourceManager.GetString("ErrorCreatingFileHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} deleting file &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorDeletingFile {
            get {
                return ResourceManager.GetString("ErrorDeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} deleting folder &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorDeletingFolder {
            get {
                return ResourceManager.GetString("ErrorDeletingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} getting names security info while getting file owner for file &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorGettingSecurityInfo {
            get {
                return ResourceManager.GetString("ErrorGettingSecurityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} looking up account SID while getting file owner for file &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorLookingUpSid {
            get {
                return ResourceManager.GetString("ErrorLookingUpSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} marking file &apos;{1}&apos; for deletion after reboot: {2}.
        /// </summary>
        public static string ErrorMarkingFileForDeletion {
            get {
                return ResourceManager.GetString("ErrorMarkingFileForDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} moving file &apos;{1}&apos; to &apos;{2}&apos;: {3}.
        /// </summary>
        public static string ErrorMovingFile {
            get {
                return ResourceManager.GetString("ErrorMovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} moving directory &apos;{1}&apos; to &apos;{2}&apos;: {3}.
        /// </summary>
        public static string ErrorMovingFolder {
            get {
                return ResourceManager.GetString("ErrorMovingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} reading from file: {1}.
        /// </summary>
        public static string ErrorReadFile {
            get {
                return ResourceManager.GetString("ErrorReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} seeking in file: {1}.
        /// </summary>
        public static string ErrorSeek {
            get {
                return ResourceManager.GetString("ErrorSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} setting file last access time &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorSettingAccessTime {
            get {
                return ResourceManager.GetString("ErrorSettingAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} setting file attribute of file &apos;{1}&apos; to &apos;{2}&apos;: {3}.
        /// </summary>
        public static string ErrorSettingAttributes {
            get {
                return ResourceManager.GetString("ErrorSettingAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} setting file creation time &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorSettingCreationTime {
            get {
                return ResourceManager.GetString("ErrorSettingCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} setting file last write time &apos;{1}&apos;: {2}.
        /// </summary>
        public static string ErrorSettingsWriteTime {
            get {
                return ResourceManager.GetString("ErrorSettingsWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error {0} writing to file: {1}.
        /// </summary>
        public static string ErrorWriteFile {
            get {
                return ResourceManager.GetString("ErrorWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to File &apos;{0}&apos; does not exist..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Folder &apos;{0}&apos; does not exist..
        /// </summary>
        public static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error during file operation, tried more than {0} times..
        /// </summary>
        public static string TriedTooOften {
            get {
                return ResourceManager.GetString("TriedTooOften", resourceCulture);
            }
        }
    }
}
