//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZetaLongPaths.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZetaLongPaths.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to remote share “{0}”: {1}.
        /// </summary>
        internal static string ErrorConnectingToRemoteShare {
            get {
                return ResourceManager.GetString("ErrorConnectingToRemoteShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} copying file “{1}” to “{2}”: {3}.
        /// </summary>
        internal static string ErrorCopyingFile {
            get {
                return ResourceManager.GetString("ErrorCopyingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} creating directory “{1}”: {2}.
        /// </summary>
        internal static string ErrorCreatingDirectory {
            get {
                return ResourceManager.GetString("ErrorCreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} creating file handle for file path “{1}”: {2}.
        /// </summary>
        internal static string ErrorCreatingFileHandle {
            get {
                return ResourceManager.GetString("ErrorCreatingFileHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} deleting file “{1}”: {2}.
        /// </summary>
        internal static string ErrorDeletingFile {
            get {
                return ResourceManager.GetString("ErrorDeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} deleting folder “{1}”: {2}.
        /// </summary>
        internal static string ErrorDeletingFolder {
            get {
                return ResourceManager.GetString("ErrorDeletingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string ErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} getting names security info while getting file owner for file “{1}”: {2}.
        /// </summary>
        internal static string ErrorGettingSecurityInfo {
            get {
                return ResourceManager.GetString("ErrorGettingSecurityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} looking up account SID while getting file owner for file “{1}”: {2}.
        /// </summary>
        internal static string ErrorLookingUpSid {
            get {
                return ResourceManager.GetString("ErrorLookingUpSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} marking file “{1}” for deletion after reboot: {2}.
        /// </summary>
        internal static string ErrorMarkingFileForDeletion {
            get {
                return ResourceManager.GetString("ErrorMarkingFileForDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} moving file “{1}” to “{2}”: {3}.
        /// </summary>
        internal static string ErrorMovingFile {
            get {
                return ResourceManager.GetString("ErrorMovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} moving directory “{1}” to “{2}”: {3}.
        /// </summary>
        internal static string ErrorMovingFolder {
            get {
                return ResourceManager.GetString("ErrorMovingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} reading from file: {1}.
        /// </summary>
        internal static string ErrorReadFile {
            get {
                return ResourceManager.GetString("ErrorReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} seeking in file: {1}.
        /// </summary>
        internal static string ErrorSeek {
            get {
                return ResourceManager.GetString("ErrorSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} setting file last access time “{1}”: {2}.
        /// </summary>
        internal static string ErrorSettingAccessTime {
            get {
                return ResourceManager.GetString("ErrorSettingAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} setting file attribute of file “{1}” to “{2}”: {3}.
        /// </summary>
        internal static string ErrorSettingAttributes {
            get {
                return ResourceManager.GetString("ErrorSettingAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} setting file creation time “{1}”: {2}.
        /// </summary>
        internal static string ErrorSettingCreationTime {
            get {
                return ResourceManager.GetString("ErrorSettingCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} setting file last write time “{1}”: {2}.
        /// </summary>
        internal static string ErrorSettingsWriteTime {
            get {
                return ResourceManager.GetString("ErrorSettingsWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} writing to file: {1}.
        /// </summary>
        internal static string ErrorWriteFile {
            get {
                return ResourceManager.GetString("ErrorWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File “{0}” does not exist..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder “{0}” does not exist..
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid paths characters..
        /// </summary>
        internal static string InvalidPathsCharacters {
            get {
                return ResourceManager.GetString("InvalidPathsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during operation, tried more than {0} times..
        /// </summary>
        internal static string TriedTooOftenPlural {
            get {
                return ResourceManager.GetString("TriedTooOftenPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during operation, tried more than {0} time..
        /// </summary>
        internal static string TriedTooOftenSingular {
            get {
                return ResourceManager.GetString("TriedTooOftenSingular", resourceCulture);
            }
        }
    }
}
